### ISSUE TITLE
还有这种操作?

### ISSUE THREAD

**Issue by shn7798** [pcdack/SDMUSIC#3]
https://github.com/pcdack/SDMUSIC/blob/0dff76797dad9c285ab1d0f90f99eb9d9a2465f9/src/sd_music/net/kugou_api.py#L14

**Comment by pcdack** [comment]
emmmm...python只学了两三天，这里这样写可能不是特别优雅。我试过用super.timeout赋值，但是失败了。所以就只能这样了。请赐教

**Comment by shn7798** [comment]
我也不是非常精通python所以以为这是什么新语法，一般是`super().__init__(timeout)`或者`super(BaseApi, self).__init__(timeout)`
